#ifndef VERSIONDOWNLOADER_GLOBAL_H
#define VERSIONDOWNLOADER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(VERSIONDOWNLOADER_LIBRARY)
#  define VERSIONDOWNLOADER_EXPORT Q_DECL_EXPORT
#else
#  define VERSIONDOWNLOADER_EXPORT Q_DECL_IMPORT
#endif

#endif // VERSIONDOWNLOADER_GLOBAL_H
